name: facebook-political-ads-emotion
channels:
  - defaults
  - conda-forge
dependencies:
  - Sphinx
  - black
  - pandas
  - numpy
  - matplotlib
  - statsmodels
  - seaborn
  - scikit-learn
  - jupyter
  - flake8
  - wordcloud
  - beautifulsoup4
  - catboost
  - python-dotenv>=0.5.1
  - pip
  - pip:
      - afinn
      - vaderSentiment
